### ISSUE TITLE
AppVeyor build for py3 fails

### ISSUE THREAD

**Issue by WojciechMula** [WojciechMula/pyahocorasick#55]
The current config doesn't set up the environment properly and setuptools fails:

```
raise ValueError(str(list(result.keys())))
    ValueError: ['path']
```

Here are two alternative ways:
* https://blog.ionelmc.ro/2014/12/21/compiling-python-extensions-on-windows/
* http://haypo-notes.readthedocs.io/python.html#build-a-python-wheel-package-on-windows

**Comment by JB-MS** [comment]
The second link helped me out, indeed! Thanks! Only problem is, that i installed a lot of stuff (a whole bunch of MS Visual C++ stuff including patches etc...) before and i don't know which is now required to make this work. Cloning the package, installing [wheel](https://pypi.python.org/pypi/wheel) and using 'Windows SDK Command Prompt' resulted in a working install on Windows 7 64bit.

Still, it would be great if the installation with pip would work again, since we install all dependencies via a requirements.txt, which at the moment fails under Windows 7 and 10.

Cheers,
Johannes

**Comment by WojciechMula** [comment]
@JB-MS When we split repositories, I hope to sort it out. But I'll need help with Win 10, I don't have access to machine that has this system.

**Comment by JB-MS** [comment]
@WojciechMula At the moment, i also do not have access to Win 10. But i will try to help.

**Comment by WojciechMula** [comment]
It was finally fixed by @ei-grad. Thank you!
